Account for alignment on `is_plain` calculations
ros2/rosidl_typesupport_fastrtps pull request #108
Opened 2023-10-02 13:28 UTC by MiguelCompany

This shall address https://github.com/ros2/rmw_fastrtps/issues/715 by taking into consideration whether the alignment generated by the compiler is compatible with the one required by the CDR serialization.

2023-10-02 16:03 UTC, clalancette commented
Preliminary CI with this and https://github.com/ros2/system_tests/pull/530 and https://github.com/ros2/rmw_fastrtps/pull/716

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19590)](http://ci.ros2.org/job/ci_linux/19590/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14101)](http://ci.ros2.org/job/ci_linux-aarch64/14101/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20314)](http://ci.ros2.org/job/ci_windows/20314/)

2023-10-02 17:11 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +        sizeof(decltype(data->@(last_member_name_) ) )
If the last member in the message was a nested message (the `else` clause above), *and* it was a plain type itself, then I think this sizeof clause might be incorrect, right?  That is, in that case we this should be:

`offsetof(DataType, @(last_member_name_) ) + last_message_size`

where `last_message_size` is what was returned from the recursive call to `max_serialized_size`.  Does that make sense?

2023-10-02 17:22 UTC, fujitatomoya reviewed
@MiguelCompany i would like to check my understanding here.

so the problem happens for both `intra` and `inter` process communication, via `rclcpp` right. (but with `rclpy`, that is why we do not see the problem with `ros2 topic echo`?) because the root cause is the mismatch between CDR representation and in-memory data alignment?

2023-10-02 19:30 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +        sizeof(decltype(data->@(last_member_name_) ) )
(separately, uncrustify is unhappy about the indentation here, but we can wait on that until we answer the question above)

2023-10-03 08:41 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +        sizeof(decltype(data->@(last_member_name_) ) )
@clalancette > If the last member in the message was a nested message (the `else` clause above), _and_ it was a plain type itself, then I think this sizeof clause might be incorrect, right? That is, in that case we this should be:
> 
> `offsetof(DataType, @(last_member_name_) ) + last_message_size`
> 
> where `last_message_size` is what was returned from the recursive call to `max_serialized_size`. Does that make sense?

I have been doing some checks with different nested types, and I got to the conclusion that you are right.

I implemented this behavior in 71b1a0fd6bd5130f711ce687644790e7c04f1e0f

2023-10-03 08:41 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +        sizeof(decltype(data->@(last_member_name_) ) )
> (separately, uncrustify is unhappy about the indentation here, but we can wait on that until we answer the question above)

Fixed in d9ec07e809f7649dee67556d441114ec61f90ecd

2023-10-03 08:51 UTC, MiguelCompany commented
> @MiguelCompany i would like to check my understanding here.
> 
> so the problem happens for both `intra` and `inter` process communication, via `rclcpp` right. (but with `rclpy`, that is why we do not see the problem with `ros2 topic echo`?) 

This is reproduced when the sample is accessed via `rmw_take_loaned_message`. I don't know whether rclpy is using it or not.

> the root cause is the mismatch between CDR representation and in-memory data alignment?
The root cause is mismatch between CDR representation and in-memory representation due to different alignment of fields.

So what we are doing with this (and related) PR is disallowing the loans (marking the type as not plain) on those types where there is a representation mismatch.

2023-10-03 17:17 UTC, fujitatomoya commented
thanks!

just a comment.

> This is reproduced when the sample is accessed via rmw_take_loaned_message. I don't know whether rclpy is using it or not.

`rclpy` doe not have any interfaces to `rcl/rmw_take_loaned_*`, so we do not have problem. original problem comes **without** `LoanedMessage` class at all on the publisher, this is because subscriber consider `can_loan_messages` as true

https://github.com/ros2/rmw_fastrtps/blob/ad4550adea4f65fdc126423f2fec13f441c6bbaa/rmw_fastrtps_shared_cpp/src/rmw_take.cpp#L565

and then call `rcl_subscription_can_loan_messages` via `rclcpp`.

2023-10-03 18:12 UTC, clalancette requested changes
Three more small changes, then I think this will be ready for CI again.

2023-10-03 18:12 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +      inner_size =
```suggestion
      inner_size =
```

2023-10-03 18:12 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> +    DataType * data;
```suggestion
```

(it is unused now)

2023-10-03 18:12 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
> +    DataType * data;
```suggestion
```

2023-10-03 19:42 UTC, MiguelCompany commented
@clalancette Applied your suggestions on 0de64df90ddad1ceab2c7dafd4a6e0a8c4a33f91

2023-10-03 20:04 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19592)](http://ci.ros2.org/job/ci_linux/19592/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14103)](http://ci.ros2.org/job/ci_linux-aarch64/14103/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20316)](http://ci.ros2.org/job/ci_windows/20316/)

2023-10-04 12:24 UTC, merged

2023-11-08 20:42 UTC, fujitatomoya commented
@Mergifyio backport iron humble

2023-11-08 20:46 UTC, fujitatomoya commented
@clalancette since i do not have write permission on this repo, can you do me a favor?

2023-11-08 20:47 UTC, clalancette commented
@Mergifyio backport iron humble