Improve wide string (de)serialization
ros2/rosidl_typesupport_fastrtps pull request #113
Opened 2024-02-20 16:04 UTC by MiguelCompany

This PR changes (de)serialization of wide strings so they don't perform `u16string` <-> `wstring` conversions

2024-02-26 16:21 UTC, MiguelCompany commented
@clalancette This one is ready for review. It is similar to ros2/rmw_fastrtps#740 (already merged) but for the static type support. I've run the tests in the `test_communication` package and they passed.

We will base the upgrade to Fast CDR 2 on the changes here.

2024-02-29 06:14 UTC, EduPonz approved these changes
Changes LGTM. I'm only wondering if we should consider removing `u16string_to_wstring` and `wstring_to_u16string`

2024-03-15 13:09 UTC, clalancette requested changes
I've left some comments about the sizes of things that we should think about.

Just so I understand; is the goal here to make sure we don't convert from `rosidl_runtime_c__U16String` to `std::wstring`, and then serialize the `wstring` into Cdr?  Instead, we serialize directly from the `rosidl_runtime_c__U16String` into Cdr?  I don't have any problem with it, but can you explain why?

Finally, to address @eduponz point about removing `u16string_to_wstring` and `wstring_to_u16string`; I don't think we should do that, at least not for this release.  That's because they are public functions and someone may be depending on them.  If we think they don't have value anymore, we can mark them as `deprecated` for this release, and then remove them in the next.

2024-03-15 13:09 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    u16str.data[i] = static_cast<char16_t>(c);
Same questions here about the sizes; this seems like we should extract a uint16_t, then cast it into a `uint_least16_t` to put it into the array.

2024-03-15 13:09 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +  auto len = static_cast<uint32_t>(u16str.size());
Same comment here about `u16str.size()` overflowing and being larger than what we can store in a uint32_t.  Add an assert or throw an exception if it is too large.

2024-03-15 13:09 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str[i]);
Same comments here about using a uint32_t here.

2024-03-15 13:09 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +    uint32_t c;
Same comment about using a uint32_t here.

2024-03-18 11:50 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +  auto len = static_cast<uint32_t>(u16str.size);
The CDR serialization of a string of any type is that of a sequence of characters. The length of sequences in CDR is serialized with a 32-bit unsigned integer.

In 349d1c9e5f5c2edef74e3f59c8f5975a85601f20 I have added a check that throws `std::overflow_error` if the string is larger than 4G characters (that's near 1000 times the length of the Bible [here](https://www.gutenberg.org/ebooks/10))

2024-03-18 11:58 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str.data[i]);
The main reason is interoperability / backward compatibility. The serialization of the `wstring` is using 4 bytes per character.

I initially did what you suggest, and used a `uint16_t`, but changed it when the tests in `test_communication` failed between `rmw_cyclonedds` and `rmw_fastrtps` for `WStrings` type.

2024-03-18 12:00 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str.data[i]);
Note: we can change this in the future if we don't mind breaking backward compatibility, but should do it at the same time in all DDS-based RMW implementations

2024-03-18 12:01 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +  auto len = static_cast<uint32_t>(u16str.size());
349d1c9e5f5c2edef74e3f59c8f5975a85601f20

2024-03-18 12:02 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str[i]);
Same answer: https://github.com/ros2/rosidl_typesupport_fastrtps/pull/113#discussion_r1528411006

2024-03-18 12:05 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    u16str.data[i] = static_cast<char16_t>(c);
Same reasoning as in [here](https://github.com/ros2/rosidl_typesupport_fastrtps/pull/113#discussion_r1528411006).

2024-03-18 12:08 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    u16str.data[i] = static_cast<char16_t>(c);
I added a check that throws an exception if the deserialized `uint32_t` does not fit into a `uint16_t` in commit c4eb425b8d2d62bfcd410a9cbb20107d97a11233. Note that this would be captured up in `rmw_fastrtps` code, since it is a `fastcdr` exception

2024-03-18 12:09 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +    uint32_t c;
Same answer as [here](https://github.com/ros2/rosidl_typesupport_fastrtps/pull/113#discussion_r1528424420)

2024-03-18 14:23 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +  auto len = static_cast<uint32_t>(u16str.size);
That works great for me, thanks.

2024-03-18 14:23 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str.data[i]);
Ah, got it.  OK, interoperability is a really good reason.

In that case, I'm totally fine with leaving this as-is, but please put in a comment saying that we are using uint32_t for the interoperability reason.

2024-03-18 14:24 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp
> +  auto len = static_cast<uint32_t>(u16str.size());
Looks great.

2024-03-18 14:25 UTC, clalancette requested changes
The code here looks good to me.  I'm just going to request some comments about why we are using `uint32_t` instead of `uint16_t` when serializing/deserializing, as well as marking the functions we are no longer using as `deprecated`.  Then we can run CI on this.

2024-03-18 15:58 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    uint32_t c = static_cast<uint32_t>(u16str.data[i]);
f9a8358

2024-03-18 15:58 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp
> +    u16str.data[i] = static_cast<char16_t>(c);
f9a8358

2024-03-18 15:59 UTC, MiguelCompany commented
> The code here looks good to me. I'm just going to request some comments about why we are using `uint32_t` instead of `uint16_t` when serializing/deserializing, as well as marking the functions we are no longer using as `deprecated`. Then we can run CI on this.

@clalancette I added two commits addressing the two points you mention here.

2024-03-19 19:18 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20498)](http://ci.ros2.org/job/ci_linux/20498/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14900)](http://ci.ros2.org/job/ci_linux-aarch64/14900/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21249)](http://ci.ros2.org/job/ci_windows/21249/)

2024-03-19 21:34 UTC, clalancette commented
Oh.  Right.  Tests are throwing warnings because they are using the deprecated methods.

I think what we should do here is to update those tests to use the new helpers instead, which will still test what we are trying to test, and fix the warnings.

2024-03-20 11:04 UTC, MiguelCompany commented
@clalancette I updated the tests here and also fixed some linting issues.

2024-03-20 12:08 UTC, clalancette commented
All right, here is another shot at CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20508)](http://ci.ros2.org/job/ci_linux/20508/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14907)](http://ci.ros2.org/job/ci_linux-aarch64/14907/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21256)](http://ci.ros2.org/job/ci_windows/21256/)

2024-03-20 18:29 UTC, clalancette approved these changes

2024-03-20 18:30 UTC, merged