Support Fast CDR v2
ros2/rosidl_typesupport_fastrtps pull request #114
Opened 2024-02-29 09:45 UTC by MiguelCompany

This makes the necessary changes to allow building with Fast CDR v2

It is built on top of #113

2024-03-20 18:34 UTC, clalancette requested changes
I think this one needs to be rebased on top #113 (at least, it seems to me that includes some of the same changes).

Once that is done I'll do another review.

2024-03-21 12:54 UTC, clalancette requested changes
A couple of small changes here.

2024-03-21 12:54 UTC, clalancette commented on rosidl_typesupport_fastrtps_c/package.xml
> +  <depend version_gte="2">fastcdr</depend>
Same comment as in https://github.com/ros2/rmw_fastrtps/pull/746#discussion_r1532601464

2024-03-21 12:54 UTC, clalancette commented on rosidl_typesupport_fastrtps_cpp/package.xml
> +  <depend version_gte="2">fastcdr</depend>
Same comment as in https://github.com/ros2/rmw_fastrtps/pull/746#discussion_r1532601464

2024-03-21 13:25 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/package.xml
> +  <depend version_gte="2">fastcdr</depend>
I did it, but didn't push: a725fbb

2024-03-21 13:25 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_cpp/package.xml
> +  <depend version_gte="2">fastcdr</depend>
I did it, but didn't push: a725fbb

2024-03-21 13:44 UTC, clalancette approved these changes

2024-03-21 14:32 UTC, MiguelCompany commented
@clalancette The tests that were updated in #113 were not updated here. I've fixed that in 7fb44ae

2024-03-26 12:04 UTC, merged