Remove fastrtps dependency
ros2/rosidl_typesupport_fastrtps pull request #68
Opened 2021-03-30 23:22 UTC by asorbini

This PR updates packages `rosidl_typesupport_fastrtps_c` and `rosidl_typesupport_fastrtps_cpp` to remove their dependency from `fastrtps`, since they only require the `fastcdr` libraries.

This change should allow `rmw_connextdds` (which also relies on these type supports) to avoid an indirect dependency on `fastrtps`.

2021-03-31 05:50 UTC, MiguelCompany requested changes
We are a bit picky about product names...

2021-03-31 05:50 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in
> +    "Could not find eProsima fastcdr: skipping rosidl_typesupport_fastrtps_c"
```suggestion
    "Could not find eProsima Fast CDR: skipping rosidl_typesupport_fastrtps_c"
```

2021-03-31 05:50 UTC, MiguelCompany commented on rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in
> +    "Could not find eProsima fastcdr - skip rosidl_typesupport_fastrtps_cpp"
```suggestion
    "Could not find eProsima Fast CDR - skip rosidl_typesupport_fastrtps_cpp"
```

2021-03-31 13:04 UTC, clalancette reviewed
The change seems reasonable to me, once @MiguelCompany 's concerns are fixed.  Though I'd want to run a full CI on this just to be sure we aren't breaking anything downstream.

2021-03-31 20:16 UTC, MiguelCompany approved these changes
LGTM

2021-03-31 20:22 UTC, asorbini commented
some CI jobs to validate:

- ci_linux: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14176)](https://ci.ros2.org/job/ci_linux/14176/)
- ci_osx: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11858)](https://ci.ros2.org/job/ci_osx/11858/)
- ci_windows: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14277)](https://ci.ros2.org/job/ci_windows/14277/)

2021-04-08 18:16 UTC, hidmic commented
Test failures appear unrelated. @asorbini consider running `aarch64` CI as well.

2021-04-08 18:29 UTC, hidmic approved these changes

2021-04-08 19:12 UTC, asorbini commented
ci_linux-aarch64: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9096)](https://ci.ros2.org/job/ci_linux-aarch64/9096/)

2021-04-14 00:44 UTC, asorbini commented
@clalancette @hidmic What are the chances of this PR getting into Galactic?

2021-04-29 19:36 UTC, hidmic commented
This PR's good to go. It was a bit late for Galactic though. Unless @cottsay thinks it's worth backporting?

I'll merge now. Thanks for your patience @asorbini.

2021-04-29 19:36 UTC, merged

2021-04-29 19:42 UTC, cottsay commented
I'd really like to see this change in Galactic, but you're right, it's a bit late.

Let's see how things shake out in Rolling and consider this for Galactic Patch 1.

2021-05-05 17:30 UTC, azeey commented
Looks like there's a regression in buildfarm_perf_tests from this. I've created a ticket there since I thought the we probably need to fix it there. https://github.com/ros2/buildfarm_perf_tests/issues/100